import { z } from 'zod';
import { publicProcedure } from '../../../create-context';

const getActiveSessionsSchema = z.object({
  type: z.enum(['video', 'audio', 'all']).default('all'),
  category: z.string().optional(),
  limit: z.number().min(1).max(50).default(20),
  offset: z.number().min(0).default(0),
});

export const getActiveSessionsProcedure = publicProcedure
  .input(getActiveSessionsSchema)
  .query(async ({ input }) => {
    const { type, category, limit, offset } = input;
    
    // Mock active sessions data with more virtual audio streams
    const mockSessions = [
      // Audio Live Streams (Virtual)
      {
        id: 'audio_session_1',
        hostId: 'audio_user_1',
        hostName: 'محمد علي حسن',
        hostAvatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=100&h=100&fit=crop&crop=face',
        title: 'جلسة موسيقية هادئة - أغاني عربية كلاسيكية',
        description: 'أجمل الأغاني العربية الكلاسيكية والطرب الأصيل',
        type: 'audio' as const,
        category: 'music',
        viewerCount: 1834,
        isLive: true,
        thumbnail: 'https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?w=300&h=200&fit=crop',
        startedAt: new Date(Date.now() - 1800000),
        tags: ['موسيقى', 'عربي', 'كلاسيك', 'طرب'],
      },
      {
        id: 'audio_session_2',
        hostId: 'audio_user_2',
        hostName: 'نور الدين عبدالله',
        hostAvatar: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=100&h=100&fit=crop&crop=face',
        title: 'بودكاست مباشر - قصص ملهمة من التاريخ',
        description: 'قصص وحكايات ملهمة من التاريخ العربي والإسلامي',
        type: 'audio' as const,
        category: 'podcast',
        viewerCount: 987,
        isLive: true,
        thumbnail: 'https://images.unsplash.com/photo-1478737270239-2f02b77fc618?w=300&h=200&fit=crop',
        startedAt: new Date(Date.now() - 2400000),
        tags: ['بودكاست', 'تاريخ', 'قصص', 'ملهمة'],
      },
      {
        id: 'audio_session_3',
        hostId: 'audio_user_3',
        hostName: 'مريم سالم أحمد',
        hostAvatar: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=100&h=100&fit=crop&crop=face',
        title: 'قراءة شعر مباشرة - أمسية أدبية رائعة',
        description: 'أمسية شعرية مع أجمل القصائد العربية الكلاسيكية',
        type: 'audio' as const,
        category: 'literature',
        viewerCount: 756,
        isLive: true,
        thumbnail: 'https://images.unsplash.com/photo-1481627834876-b7833e8f5570?w=300&h=200&fit=crop',
        startedAt: new Date(Date.now() - 3600000),
        tags: ['شعر', 'أدب', 'قراءة', 'أمسية'],
      },
      {
        id: 'audio_session_4',
        hostId: 'audio_user_4',
        hostName: 'أحمد الموسيقار',
        hostAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100&h=100&fit=crop&crop=face',
        title: 'عزف عود مباشر - مقامات شرقية أصيلة',
        description: 'عزف مباشر على آلة العود مع أجمل المقامات الشرقية',
        type: 'audio' as const,
        category: 'music',
        viewerCount: 2145,
        isLive: true,
        thumbnail: 'https://images.unsplash.com/photo-1511379938547-c1f69419868d?w=300&h=200&fit=crop',
        startedAt: new Date(Date.now() - 1200000),
        tags: ['عود', 'مقامات', 'موسيقى', 'شرقي'],
      },
      {
        id: 'audio_session_5',
        hostId: 'audio_user_5',
        hostName: 'فاطمة المقرئة',
        hostAvatar: 'https://images.unsplash.com/photo-1494790108755-2616b612b786?w=100&h=100&fit=crop&crop=face',
        title: 'تلاوة قرآنية مباشرة - صوت هادئ ومريح',
        description: 'تلاوة مباشرة للقرآن الكريم بصوت هادئ ومريح للنفس',
        type: 'audio' as const,
        category: 'religious',
        viewerCount: 3421,
        isLive: true,
        thumbnail: 'https://images.unsplash.com/photo-1542816417-0983c9c9ad53?w=300&h=200&fit=crop',
        startedAt: new Date(Date.now() - 900000),
        tags: ['قرآن', 'تلاوة', 'ديني', 'هادئ'],
      },
      {
        id: 'audio_session_6',
        hostId: 'audio_user_6',
        hostName: 'سامي الراوي',
        hostAvatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=100&h=100&fit=crop&crop=face',
        title: 'حكايات شعبية - من التراث العربي',
        description: 'حكايات وقصص شعبية من التراث العربي الأصيل',
        type: 'audio' as const,
        category: 'storytelling',
        viewerCount: 1567,
        isLive: true,
        thumbnail: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=300&h=200&fit=crop',
        startedAt: new Date(Date.now() - 2100000),
        tags: ['حكايات', 'تراث', 'شعبي', 'قصص'],
      },
      {
        id: 'audio_session_7',
        hostId: 'audio_user_7',
        hostName: 'ليلى المطربة',
        hostAvatar: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=100&h=100&fit=crop&crop=face',
        title: 'غناء مباشر - أغاني فيروز الخالدة',
        description: 'غناء مباشر لأجمل أغاني فيروز والطرب الأصيل',
        type: 'audio' as const,
        category: 'music',
        viewerCount: 2789,
        isLive: true,
        thumbnail: 'https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?w=300&h=200&fit=crop',
        startedAt: new Date(Date.now() - 1500000),
        tags: ['غناء', 'فيروز', 'طرب', 'كلاسيك'],
      },
      {
        id: 'audio_session_8',
        hostId: 'audio_user_8',
        hostName: 'عبدالرحمن الواعظ',
        hostAvatar: 'https://images.unsplash.com/photo-1507591064344-4c6ce005b128?w=100&h=100&fit=crop&crop=face',
        title: 'درس ديني مباشر - فقه العبادات',
        description: 'درس ديني مباشر في فقه العبادات والأحكام الشرعية',
        type: 'audio' as const,
        category: 'religious',
        viewerCount: 1890,
        isLive: true,
        thumbnail: 'https://images.unsplash.com/photo-1542816417-0983c9c9ad53?w=300&h=200&fit=crop',
        startedAt: new Date(Date.now() - 2700000),
        tags: ['ديني', 'فقه', 'عبادات', 'أحكام'],
      },
      {
        id: 'audio_session_9',
        hostId: 'audio_user_9',
        hostName: 'خالد الإذاعي',
        hostAvatar: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=100&h=100&fit=crop&crop=face',
        title: 'برنامج إذاعي - أخبار ونقاشات يومية',
        description: 'برنامج إذاعي يومي مع آخر الأخبار والنقاشات المهمة',
        type: 'audio' as const,
        category: 'news',
        viewerCount: 3456,
        isLive: true,
        thumbnail: 'https://images.unsplash.com/photo-1478737270239-2f02b77fc618?w=300&h=200&fit=crop',
        startedAt: new Date(Date.now() - 600000),
        tags: ['إذاعة', 'أخبار', 'نقاش', 'يومي'],
      },
      {
        id: 'audio_session_10',
        hostId: 'audio_user_10',
        hostName: 'زينب المحاضرة',
        hostAvatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=100&h=100&fit=crop&crop=face',
        title: 'محاضرة تطوير الذات - كيف تحقق أهدافك',
        description: 'محاضرة مباشرة في تطوير الذات وتحقيق الأهداف الشخصية',
        type: 'audio' as const,
        category: 'education',
        viewerCount: 2234,
        isLive: true,
        thumbnail: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=300&h=200&fit=crop',
        startedAt: new Date(Date.now() - 1800000),
        tags: ['تطوير', 'ذات', 'أهداف', 'تحفيز'],
      },
      {
        id: 'audio_session_11',
        hostId: 'audio_user_11',
        hostName: 'يوسف الكوميدي',
        hostAvatar: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=100&h=100&fit=crop&crop=face',
        title: 'كوميديا صوتية - نكت وضحك بلا حدود',
        description: 'جلسة كوميديا صوتية مليئة بالضحك والنكت المرحة',
        type: 'audio' as const,
        category: 'comedy',
        viewerCount: 4567,
        isLive: true,
        thumbnail: 'https://images.unsplash.com/photo-1513475382585-d06e58bcb0e0?w=300&h=200&fit=crop',
        startedAt: new Date(Date.now() - 3000000),
        tags: ['كوميديا', 'ضحك', 'نكت', 'ترفيه'],
      },
      {
        id: 'audio_session_12',
        hostId: 'audio_user_12',
        hostName: 'منى الطبيبة',
        hostAvatar: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=100&h=100&fit=crop&crop=face',
        title: 'استشارات طبية مباشرة - صحتك تهمنا',
        description: 'استشارات طبية مباشرة ونصائح صحية مهمة للجميع',
        type: 'audio' as const,
        category: 'health',
        viewerCount: 1678,
        isLive: true,
        thumbnail: 'https://images.unsplash.com/photo-1559757148-5c350d0d3c56?w=300&h=200&fit=crop',
        startedAt: new Date(Date.now() - 2400000),
        tags: ['طب', 'صحة', 'استشارات', 'نصائح'],
      },
      // Regular Video Streams
      {
        id: 'session_1',
        hostId: 'user_1',
        hostName: 'أحمد محمد',
        hostAvatar: 'https://picsum.photos/100/100?random=1',
        title: 'بث مباشر - دردشة مع المتابعين',
        description: 'دردشة مفتوحة مع المتابعين والرد على الأسئلة',
        type: 'video' as const,
        category: 'chat',
        viewerCount: 2847,
        isLive: true,
        thumbnail: 'https://picsum.photos/300/200?random=1',
        startedAt: new Date(Date.now() - 1800000),
        tags: ['دردشة', 'تفاعل', 'أسئلة'],
      },
      {
        id: 'session_2',
        hostId: 'user_2',
        hostName: 'فاطمة علي',
        hostAvatar: 'https://picsum.photos/100/100?random=2',
        title: 'طبخ مع فاطمة - وصفات رمضانية',
        description: 'تعلمي أشهى الوصفات الرمضانية',
        type: 'video' as const,
        category: 'cooking',
        viewerCount: 4521,
        isLive: true,
        thumbnail: 'https://picsum.photos/300/200?random=2',
        startedAt: new Date(Date.now() - 900000),
        tags: ['طبخ', 'رمضان', 'وصفات'],
      },
      {
        id: 'session_3',
        hostId: 'user_3',
        hostName: 'محمد حسن',
        hostAvatar: 'https://picsum.photos/100/100?random=3',
        title: 'نقاش مفتوح - التكنولوجيا والمستقبل',
        description: 'حوار حول تأثير التكنولوجيا على حياتنا',
        type: 'video' as const,
        category: 'talk',
        viewerCount: 1890,
        isLive: true,
        thumbnail: 'https://picsum.photos/300/200?random=3',
        startedAt: new Date(Date.now() - 2700000),
        tags: ['تكنولوجيا', 'نقاش', 'مستقبل'],
      },
    ];
    
    // Filter by type if specified
    let filteredSessions = mockSessions;
    if (type !== 'all') {
      filteredSessions = mockSessions.filter(session => session.type === type);
    }
    
    // Filter by category if specified
    if (category) {
      filteredSessions = filteredSessions.filter(session => session.category === category);
    }
    
    // Apply pagination
    const paginatedSessions = filteredSessions.slice(offset, offset + limit);
    
    return {
      sessions: paginatedSessions,
      total: filteredSessions.length,
      hasMore: offset + limit < filteredSessions.length,
    };
  });